// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS2jJA6H3tKtVDxSUtCcEMxuTZacX2wGY',
    appId: '1:397649372252:web:395f128435aed32f687299',
    messagingSenderId: '397649372252',
    projectId: 'neuromathixfyp',
    authDomain: 'neuromathixfyp.firebaseapp.com',
    storageBucket: 'neuromathixfyp.firebasestorage.app',
    measurementId: 'G-4NFBLZKLD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxeH1p6EZAd7oHeMtD7pMbOSOg2SFANzE',
    appId: '1:397649372252:android:8e1e54d6002bd586687299',
    messagingSenderId: '397649372252',
    projectId: 'neuromathixfyp',
    storageBucket: 'neuromathixfyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdr7ivz8wZPWX7xhHT7sKgt_2KuYO7DRE',
    appId: '1:397649372252:ios:2b255993890d41ad687299',
    messagingSenderId: '397649372252',
    projectId: 'neuromathixfyp',
    storageBucket: 'neuromathixfyp.firebasestorage.app',
    iosBundleId: 'com.example.neuromathix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdr7ivz8wZPWX7xhHT7sKgt_2KuYO7DRE',
    appId: '1:397649372252:ios:2b255993890d41ad687299',
    messagingSenderId: '397649372252',
    projectId: 'neuromathixfyp',
    storageBucket: 'neuromathixfyp.firebasestorage.app',
    iosBundleId: 'com.example.neuromathix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS2jJA6H3tKtVDxSUtCcEMxuTZacX2wGY',
    appId: '1:397649372252:web:d1833fe43ca57e1b687299',
    messagingSenderId: '397649372252',
    projectId: 'neuromathixfyp',
    authDomain: 'neuromathixfyp.firebaseapp.com',
    storageBucket: 'neuromathixfyp.firebasestorage.app',
    measurementId: 'G-F9FGY0LRZ5',
  );

}
